language: java
deploy:
  provider: cloudfoundry
  username: kesavansiet@gmail.com
  password: 15031999@Pk7
  api: https://api.run.pivotal.io
  organization: CollegeFeeApp
  space: development
  manifest: manifest.yml
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install
