language: java
deploy:
  provider: cloudfoundry
  username: anandhkumar59@yahoo.com
  password: Anand@558
  api: https://api.run.pivotal.io
  organization: CollegeFeeRegisterApp
  space: development
  manifest: manifest.yml
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install
